config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about'   => 'static_pages#about'
  get 'index'   => 'beams#index'
  get 'create'  => 'beams#new'
  get 'beams/update_material', as: 'update_material'

  resources :beams do
    member do
      put 'copy'
      put 'clean'
      get 'results'
      get 'embed'

    end
  end

  resources :jobs do
    member do
      put 'submit'
      put 'kill'
      get 'stdout'
    end
  end

end

app/models/beam.rb
class Beam < ActiveRecord::Base
  belongs_to :material
  belongs_to :job, dependent: :destroy
  accepts_nested_attributes_for :material
  accepts_nested_attributes_for :job
  delegate :running?, :completed?, :active?, :failed?, :ready?, :ready,
    :submitted?, :terminated?, :destroyable?, :cleanable?, :terminatable?,
    :editable?, to: :job

  validates :name,     presence: true, uniqueness: { case_sensitive: false }
  # TODO: Check name with a regex for parentheses.
  validates :length,   presence: true, numericality: { greater_than: 0 }
  validates :width,    presence: true, numericality: { greater_than: 0 }
  validates :height,   presence: true, numericality: { greater_than: 0 }
  validates :meshsize, presence: true, numericality: { greater_than: 0 }
  validates :load,     presence: true,
                       numericality: { greater_than_or_equal_to: 0 }
  validates :length_unit,        presence: true
  validates :width_unit,         presence: true
  validates :height_unit,        presence: true
  validates :meshsize_unit,      presence: true
  validates :load_unit,          presence: true
  validates :result_unit_system, presence: true
  validates :material,           presence: true

  include UnitsHelper
  include Results

  validates_inclusion_of :length_unit,   in: DIMENSIONAL_UNITS.keys.map(&:to_s)
  validates_inclusion_of :width_unit,    in: DIMENSIONAL_UNITS.keys.map(&:to_s)
  validates_inclusion_of :height_unit,   in: DIMENSIONAL_UNITS.keys.map(&:to_s)
  validates_inclusion_of :meshsize_unit, in: DIMENSIONAL_UNITS.keys.map(&:to_s)
  validates_inclusion_of :load_unit,     in: FORCE_UNITS.keys.map(&:to_s)

  # Formulate a file/directory prefix using the beam's name by removing all
  # spaces and converting to lower case.
  # TODO: Maybe add ID to prefix?  Can then strip name of characters that aren't
  # allowed in GMSH and Elmer, and still ensure some type of uniqueness.
  def prefix
    name.gsub(/\s+/, "").downcase
    # name.gsub(/\W/, "").downcase
  end

  def stress_units
    RESULT_UNITS[result_unit_system.to_sym][:stress]
  end

  def displ_units
    RESULT_UNITS[result_unit_system.to_sym][:displ]
  end

  # Calculate the beam's bending moment of inertia.
  def inertia
    convert(self, :width) * convert(self, :height)**3 / 12
  end

  # Calculate the beam's cross-sectional area.
  def area
    convert(self, :width) * convert(self, :height)
  end

  # Calculate the beam's mass.
  def mass
    convert(self, :length) * area * convert(material, :density)
  end

  # Calculate the beam's weight.
  def weight
    mass * GRAVITY
  end

  # Calculate the beam's flexural stiffness.
  def stiffness
    convert(material, :modulus) * inertia
  end

  # Calculate the total force reaction due to load and gravity.
  def force_reaction
    convert(self, :load) + weight
  end

  # Calculate the total moment reaction due to load and gravity.
  def moment_reaction
    -convert(self, :load) * convert(self, :length) + -weight * convert(self, :length) / 2
  end

  # Calculate the beam end angle due to load and gravity.
  def theta
    p = convert(self, :load)
    l = convert(self, :length)
    ei = stiffness
    w = weight

    theta_load = p * l**2 / (2 * ei) * 180 / Math::PI
    theta_grav = w * l**2 / (6 * ei) * 180 / Math::PI
    theta_load + theta_grav
  end

  # Calculate the shear modulus of the material based on the elastic modulus
  # and Poisson's ratio.
  def shear_modulus
    convert(material, :modulus) / (2 * (1 + material.poisson))
  end

  # Calculate to total displacement due to load and gravity using Timoshenko
  # theory.
  def displ
    p = convert(self, :load)
    l = convert(self, :length)
    ei = stiffness
    a = area
    w = weight
    g = shear_modulus
    k = 5.0 / 6.0

    d_load = -p * l * (l**2 / (3 * ei) + 1 / (k * a * g))
    d_grav = -w * l * (l**2 / (8 * ei) + 1 / (2 * k * a * g))
    d_load + d_grav
  end

  # Calculate the maximum pricipal stress.
  def stress
    moment_reaction.abs * convert(self, :height) / (2 * inertia)
  end

  # Calulate the simulation error with respect to beam theory prediction.
  def error(type)
    begin
      theory = self.send(type.to_s)
      fem = fem_result(type)
      theory != 0.0 && !fem.nil? ? (fem - theory) / theory * 100 : nil
    rescue
      nil
    end
  end

  def duplicate
    duplicate_beam = self.dup
    duplicate_beam.name = generate_duplicate_name
    duplicate_beam.job = Job.new
    duplicate_beam.job.config = job.config
    duplicate_beam.job.cores = job.cores
    duplicate_beam.job.machines = job.machines
    duplicate_beam.ready
    duplicate_beam
  end

  private

    # Generate a new name when copying a beam by adding the suffix "-Copy" and
    # an iterator if necessary.
    def generate_duplicate_name
      suffix = "-Copy"
      duplicate_name = name
      duplicate_name += suffix unless name.include? suffix
      iter = 1
      while Beam.where("lower(name) =?", duplicate_name.downcase).first
        duplicate_name.slice!(((0...duplicate_name.length).find_all \
          { |i| duplicate_name[i, suffix.length] == suffix }.last + \
          suffix.length)...(duplicate_name.length))
        duplicate_name += iter.to_s
        iter += 1
      end
      duplicate_name
    end
end

app/controllers/beams_controller.rb
class BeamsController < ApplicationController
  before_action :set_beam, only: [:show, :results, :edit, :update, :destroy,
    :clean, :copy, :embed]
  before_action :get_displayed_result, only: [:results, :embed]
  before_action :get_last_page, only: [:destroy]

  def index
    if Beam.count > 0
      @beams = Beam.order(:id).page params[:page]
    else
      redirect_to root_url
    end
  end

  def new
    @beam = Beam.new
  end

  def show
  end

  def edit
  end

  def results
  end

  def create
    @beam = Beam.new(beam_params)
    if @beam.save
      flash[:success] = "Successfully created #{@beam.name}."
      redirect_to @beam
    else
      render 'new'
    end
  end

  def update
    if @beam.editable?
      if @beam.update_attributes(beam_params)
        @beam.job.delete_staging_directories
        @beam.ready
        flash[:success] = "Successully updated #{@beam.name}."
        redirect_to @beam
      else
        render 'edit'
      end
    else
      flash[:danger] = "#{@beam.name} is not editable at this time."
      render 'edit'
    end
  end

  def destroy
    if @beam.destroyable?
      @beam.job.delete_staging_directories
      @beam.destroy
      flash[:success] = "Beam deleted."
    else
      flash[:danger] = "Beam cannot be deleted at this time."
    end

    if request.referrer.include? index_path
      if @last_page > Beam.page.num_pages
        redirect_to index_path(page: Beam.page.num_pages)
      else
        redirect_to request.referrer
      end
    else
      redirect_to index_url
    end
  end

  def clean
    if @beam.cleanable?
      @beam.job.delete_staging_directories
      @beam.ready
      flash[:success] = "Job directory successfully deleted."
    else
      flash[:danger] = "Beam cannot be cleaned at this time."
    end

    if request.referrer.include? results_beam_path
      redirect_to @beam
    else
      redirect_to request.referrer || index_url
    end
  end

  def copy
    duplicate_beam = @beam.duplicate
    if duplicate_beam.save
      if request.referrer.include? index_path
        redirect_to index_path(page:   Beam.page.num_pages,
                               anchor: duplicate_beam.prefix)
      else
        redirect_to duplicate_beam
      end
    else
      flash[:danger] = "Unable to copy #{@beam.name}."
      redirect_to request.referrer
    end
  end

  def embed
    render layout: false, file: @beam.graphics_file(@result.to_sym)
  end

  def update_material
    @material_id = params[:material_id].to_i
  end

  private

    def beam_params
      params.require(:beam).permit(:name, :length, :width, :height, :meshsize,
                                   :load, :length_unit, :width_unit, :material_id,
                                   :height_unit, :meshsize_unit, :load_unit,
                                   :result_unit_system, job_attributes: [:cores,
                                   :machines, :config, :id] )
    end

    def set_beam
      @beam = Beam.find(params[:id])
    end

    def get_displayed_result
      @result = params[:result].nil? ? "stress" : params[:result]
    end

    # Get the last visited paginated index page when destroying beam.  This
    # provides input to handle a redirect to the previous pagination if the
    # beam being deleted is the last one on the page.
    def get_last_page
      query = URI.parse(request.referrer).query
      @last_page = query.nil? ? 0 : CGI.parse(query)["page"].first.to_i
    end
end

app/helpers/beams_helper.rb
module BeamsHelper

  def number_with_units(object, param, **opts)
    precision = opts[:precision].nil? ? 4 : opts[:precision]
    is_result = opts[:is_result].nil? ? false : true
    if is_result
      number = unconvert(object, param)
      significant = true
    else
      number = object.send(param.to_s)
      significant = false
    end

    value = number_with_precision(number,
                                  precision: precision,
                                  significant: significant,
                                  strip_insignificant_zeros: true)
    unit = unit_text(object, param, is_result)

    "#{value} #{unit}".html_safe
  end

  def button(beam, type, opts = { text: false, size: 'btn-xs',
    disabled: false })

    if type == :submit
      link_to "<span class='glyphicon glyphicon-flash'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        submit_job_path(beam.job),
        method: :put,
        class: "btn btn-success #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'Submit job to cluster'
    elsif type == :edit
      link_to "<span class='glyphicon glyphicon-pencil'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        edit_beam_path(beam),
        class: "btn btn-fteblue #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'Edit beam'
    elsif type == :delete
      link_to "<span class='glyphicon glyphicon-trash'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        beam,
        method: :delete,
        class: "btn btn-ftered #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { confirm: 'Are you sure?', toggle: 'tooltip',
          placement: 'top' },
        title: 'Delete beam'
    elsif type == :copy
      link_to "<span class='glyphicon glyphicon-duplicate'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        copy_beam_path(beam),
        method: :put,
        class: "btn btn-ftegray #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'Copy beam'
    elsif type == :clean
      link_to "<span class='glyphicon glyphicon-erase'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        clean_beam_path(beam),
        method: :put,
        class: "btn btn-fteyellow #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'Clean job directory'
    elsif type == :results
      link_to "<span class='glyphicon glyphicon-stats'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        results_beam_path(beam),
        class: "btn btn-primary #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'View results'
    elsif type == :refresh
      link_to "<span class='glyphicon glyphicon-refresh'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        request.original_url,
        class: "btn btn-info #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'Refresh page'
    elsif type == :kill
      link_to "<span class='glyphicon glyphicon-remove'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        kill_job_path(beam.job),
        method: :put,
        class: "btn btn-danger #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'Kill job'
    elsif type == :stdout
      link_to "<span class='glyphicon glyphicon-open-file'></span> "\
          "#{type.capitalize if opts[:text]}".html_safe,
        stdout_job_path(beam.job),
        class: "btn btn-ftegreen #{opts[:size]} " \
          "#{'disabled' * opts[:disabled].to_i}".strip,
        data: { toggle: 'tooltip', placement: 'top' },
        title: 'View standard output',
        target: '_blank'
    end
  end

  def button_group(beam, opts = { text: false, size: 'btn-xs'} )
    div = "<div class=\"btn-group\">"
    if beam.ready?
      div += button(beam, :submit, opts)
    else
      if beam.active? || beam.running?
        div += button(beam, :kill,  opts)
        opts[:disabled] = true
      else
        div += button(beam, :clean,  opts)
      end
    end

    div += button(beam, :edit,   opts)
    div += button(beam, :copy,   opts)
    div += button(beam, :delete, opts)
    div += "</div>"
    div.html_safe
  end

  def result_table(beam, result)
    analysis_result =
      !beam.send(result.to_s<<"_fem").nil? ? number_with_units(beam,
      (result.to_s<<"_fem").to_sym, is_result: true) : "N/A"
    theory_result = number_with_units(beam, result, is_result: true)

    error = beam.error(result)
    if !error.nil?
      if error.abs <= 5
        formatted_error = content_tag(:font, "%.2f%" % error, color: "green")
      elsif error.abs <= 10
        formatted_error = content_tag(:font, "%.2f%" % error, color: "orange")
      else
        formatted_error = content_tag(:font, "%.2f%" % error, color: "red")
      end
    else
      formatted_error = "N/A"
    end

    "<td>#{analysis_result}</td>" \
    "<td>#{theory_result}</td>" \
    "<td>#{formatted_error}</td>".html_safe
  end
end

app/views/beams/_calculations.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Calculated Results</strong>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <td>Bending Moment of Inertia</td>
        <td><%= number_with_units(@beam,
                                  :inertia,
                                  is_result: true) %></td>
      </tr>
      <tr>
        <td>Mass</td>
        <td><%= number_with_units(@beam,
                                  :mass,
                                  is_result: true) %></td>
      </tr>
      <tr>
        <td>Reactive Force</td>
        <td><%= number_with_units(@beam,
                                  :force_reaction,
                                  is_result: true) %></td>
      </tr>
      <tr>
        <td>Reactive Moment</td>
        <td><%= number_with_units(@beam,
                                  :moment_reaction,
                                  is_result: true) %></td>
      </tr>
      <tr>
        <td>Maximum Angle</td>
        <td><%= number_with_precision(@beam.theta,
                                      precision: 3,
                                      significant: true) %>&#176;</tr>
      <tr>
        <td>Maximum Displacement</td>
        <td><%= number_with_units(@beam,
                                  :displ,
                                  is_result: true) %></td>
      </tr>
      <tr>
        <td>Maximum Principal Stress</td>
        <td><%= number_with_units(@beam,
                                  :stress,
                                  is_result: true) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/beams/_field.html.erb
<% if text.nil? %>
<td><%= object.to_s.capitalize %></td>
<% else %>
<td><%= text %></td>
<% end %>
<td><%= form.text_field object, class: 'form-control' %></td>
<td>
  <%= form.select (object.to_s<<"_unit").to_sym,
                  constant.map { |k,v| [v[:text], k.to_s] },
                  {},
                  { class: "form-control blue-select" } %>
</td>

app/views/beams/_form.html.erb
<%= form_for(setup_beam(@beam)) do |f| %>
  <div class="row">
    <div class="col-md-12">
      <%= render 'shared/error_messages' %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Name</strong>
        </div>
        <table class="table">
          <tbody>
            <tr><td><%= f.text_field :name, class: 'form-control' %></td></tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Dimensions</strong>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <%= render 'field', form: f, object: :length, text: nil,
                constant: DIMENSIONAL_UNITS, style: "default" %>
            </tr>
            <tr>
              <%= render 'field', form: f, object: :width, text: nil, constant:
                DIMENSIONAL_UNITS, style: "default" %>
            </tr>
            <tr>
              <%= render 'field', form: f, object: :height, text: nil,
                constant: DIMENSIONAL_UNITS, style: "default" %>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Simulation Parameters</strong>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td>Solver</td>
              <td>
                <%= f.fields_for :job do |ff| %>
                  <%= ff.select :config,
                    SOLVERS.map { |k,v| [v, k.to_s] }, {},
                    { class: "form-control blue-select" } %>
                <% end %>
              </td>
              <td></td>
            </tr>
            <tr>
              <td>Number of Nodes</td>
              <td>
                <%= f.fields_for :job do |ff| %>
                  <%= ff.select :machines,
                    (1..MAX_NODE).map { |i| [i.to_s, i] }, {},
                    { class: "form-control blue-select" } %>
                <% end %>
              </td>
              <td></td>
            </tr>
            <tr>
              <td>Processors per Node</td>
              <td>
                <%= f.fields_for :job do |ff| %>
                  <%= ff.select :cores,
                    (1..MAX_PPN).map { |i| [i.to_s, i] }, {},
                    { class: "form-control blue-select" } %>
                <% end %>
              </td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Model Parameters</strong>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <%= render 'field', form: f, object: :load, text: nil, constant:
                FORCE_UNITS, style: "default" %>
            </tr>
            <tr>
              <%= render 'field', form: f, object: :meshsize, text:
                "Global Mesh Size", constant: DIMENSIONAL_UNITS, style:
                "default" %>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Material Properties</strong>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td>Material</td>
              <td>
                <%= f.collection_select :material_id, Material.all,
                  :id, :name, {}, { class: "form-control blue-select" } %>
              </td>
            </tr>
            <tr>
              <th>Elastic Modulus (<%= unit_text(@beam.material, :modulus) %>)</th>
              <th>Poisson's Ratio</th>
              <th>Density (<%= unit_text(@beam.material, :density) %>)</th>
            </tr>
            <tr>
              <td>
                <div id="modulus">
                  <%= @beam.material.modulus %>
                </div>
              </td>
              <td>
                <div id="poisson">
                  <%= @beam.material.poisson %>
                </div>
              </td>
              <td>
                <div id="density">
                  <%= @beam.material.density %>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Post Processing</strong>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td>Result Unit System</td>
              <td>
                <%= f.select :result_unit_system,
                  RESULT_UNITS.map { |k,v| [v[:text], k.to_s] }, {},
                  { class: "form-control blue-select" } %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <%= f.submit yield(:button_text), class: "btn btn-success" %>
    </div>
  </div>
<% end %>
<script>
  $(document).ready(function() {
    $('#beam_material_id').change(function() {
      $.ajax({
        url: "<%= update_material_path %>",
        data: {
          material_id: $("#beam_material_id option:selected").val()
        },
        dataType: "script"
      });
    });
  });
</script>

app/views/beams/_graphics.html.erb
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item"
    src=<%= "embed?result=#{@result}" %>>
  </iframe>
  <div class="btn-group-vertical btn-group-results">
    <%= link_to "<strong>&sigma;<sub>zz</sub></strong>".html_safe,
      results_beam_path(@beam, result: "stress"),
      class: "btn btn-transparent",
      data: { toggle: 'tooltip', placement: 'top' },
      title: 'View stress' %>
    <%= link_to "<strong>&delta;<sub>y</sub></strong>".html_safe,
      results_beam_path(@beam, result: "displ"),
      class: "btn btn-transparent",
      data: { toggle: 'tooltip', placement: 'top' },
      title: 'View displacement' %>
    <%= link_to "<span class='glyphicon glyphicon-fullscreen'>" \
      "</span>".html_safe,
      embed_beam_path(@beam, result: params[:result]),
      class: "btn btn-transparent",
      data: { toggle: 'tooltip', placement: 'top' },
      title: 'Open in new tab',
      target: "_blank" %>
  </div>
</div>

app/views/beams/_inputs.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Input Dimensions, Loads, and Parameters</strong>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <td>Length</td>
        <td><%= number_with_units(@beam, :length) %></td>
      </tr>
      <tr>
        <td>Width</td>
        <td><%= number_with_units(@beam, :width) %></td>
      </tr>
      <tr>
        <td>Height</td>
        <td><%= number_with_units(@beam, :height) %></td>
      </tr>
      <tr>
        <td>Material</td>
        <td><%= @beam.material.name %></td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&bull; Modulus of Elasticity</td>
        <td><%= number_with_units(@beam.material, :modulus) %></td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&bull; Poisson's Ratio</td>
        <td><%= @beam.material.poisson %></td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&bull; Density</td>
        <td><%= number_with_units(@beam.material, :density) %></td>
      </tr>
      <tr>
        <td>End Load</td>
        <td><%= number_with_units(@beam, :load) %></td>
      </tr>
      <tr>
        <td>Hexogonal Mesh Size</td>
        <td><%= number_with_units(@beam, :meshsize) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/beams/_stats.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Simulation Statistics</strong>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <td>Solver</td>
        <td><%= @beam.job.config.capitalize %></td>
      </tr>
      <tr>
        <td>Requested Nodes</td>
        <td><%= @beam.job.machines %></td>
      </tr>
      <tr>
        <td>Requested CPUs/Node</td>
        <td><%= @beam.job.cores %></td>
      </tr>
      <% @beam.job.stats.each do |key,value| %>
        <tr>
          <td><%= key %></td>
          <% if value.nil? %>
            <td>N/A</td>
          <% else %>
            <td><%= value %></td>
          <% end %>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/beams/_summary.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Finite Element Analysis Summary</strong>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Analytical Result</th>
        <th>Timoshenko Theory</th>
        <th>Error</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>&delta;<sub>y</sub></td>
        <%= result_table(@beam, :displ) %>
      </tr>
      <tr>
        <td>&sigma;<sub>33</sub></td>
        <%= result_table(@beam, :stress) %>
      </tr>
    </tbody>
  </table>
</div>

app/views/beams/edit.html.erb
<% provide(:title, "Edit #{@beam.name}") %>
<% provide(:button_text, "Save changes") %>
<h1>Edit Beam</h1>
<%= render 'form' %>

app/views/beams/index.html.erb
<% provide(:title, "Beams") %>
<h1>
  Beam list
  <%= button(nil, :refresh, size: 'btn-lg') %>
</h1>
<%= paginate @beams %>
<p><%= page_entries_info @beams, entry_name: 'beam' %></p>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Status</th>
      <th>Results</th>
      <th>Solver</th>
      <th>Dimensions (L*W*H)</th>
      <th>Mesh Size</th>
      <th></th>
    </tr>
  </thead>
  <% @beams.each do |beam| %>
    <tr>
      <td><%= beam.id %></td>
      <td><%= link_to beam.name, beam, name: beam.prefix %></td>
      <td><%= status_label(beam.job) %></td>
      <td>
        <% if beam.completed? %>
          <div class="btn-group">
            <%= button(beam, :results, text: false, size: 'btn-xs') %>
          </div>
        <% elsif beam.failed? %>
          <div class="btn-group">
            <%= button(beam, :stdout,  text: false, size: 'btn-xs') %>
          </div>
        <% end %>
      </td>
      <td><%= SOLVERS[beam.job.config.to_sym] %></td>
      <td><%= number_with_units(beam, :length) %> *
          <%= number_with_units(beam, :width) %> *
          <%= number_with_units(beam, :height) %></td>
      <td><%= number_with_units(beam, :meshsize) %></td>
      <td><%= button_group(beam) %></td>
    </tr>
  <% end %>
</table>

app/views/beams/new.html.erb
<% provide(:title, "New") %>
<% provide(:button_text, "Create beam") %>
<h1>Create a new beam</h1>
<%= render 'form' %>

app/views/beams/results.html.erb
<% provide(:title, "Results") %>
<h1><%= @beam.name %> Results</h1>
<div class="row">
  <div class="col-md-6">
    <%= render 'graphics' %>
    <%= render 'summary' %>
    <%= render 'calculations' %>
  </div>
  <div class="col-md-6">
    <%= render 'stats' %>
    <%= render 'inputs' %>
  </div>
</div>
<%= button_group(@beam, text: true, size: 'btn-md') %>

app/views/beams/update_material.js.erb
$('#modulus').html("<%= Material.find(@material_id).modulus %>");
$('#poisson').html("<%= Material.find(@material_id).poisson %>");
$('#density').html("<%= Material.find(@material_id).density %>");