config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about'   => 'static_pages#about'
  get 'index'   => 'beams#index'
  get 'create'  => 'beams#new'
  get 'beams/update_material', as: 'update_material'

  resources :beams do
    member do
      put 'copy'
      put 'clean'
      get 'results'
      get 'embed'

    end
  end

  resources :jobs do
    member do
      put 'submit'
      put 'kill'
      get 'stdout'
    end
  end

end

app/views/layouts/_debug.html.erb
<% if params[:controller] == 'beams' && params[:action] == 'results' %>
  <%= debug Beam.find(params[:id]).debug_info %>
<% end %>
<%= debug(params) %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2016 Milwaukee Institute
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-default navbar-fixed-top">
      <ul class="nav navbar-header">
        <li><%= link_to image_tag("mkei_logo_155x60.png",
                                  alt: "Milwaukee Institute Logo"),
                                  'https://www.mkei.org/',
                                  id: "logo" %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><%= link_to "Cantilever Beam", root_path, id: "app-title" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to index_path do %>
            <span class="glyphicon glyphicon-list"></span> List
          <% end %>
        </li>
        <li>
          <%= link_to create_path do %>
            <span class="glyphicon glyphicon-plus"></span> Create
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application',
                            media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render 'layouts/debug', params: params if Rails.env.development? %>
    </div>
  </body>
</html>